#TODO: Provide instructions for modpack devs.
---
ModPackConfigName: null
ModPackConfigVersion: 0
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "DregoraOP"
Overworld:
  PresetName: "DregoraOP"
  DimensionId: 0
  ShowInWorldCreationGUI: true
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: ""
  GameType: "Survival"
  BonusChest: false
  AllowCheats: false
  WorldBorderRadiusInChunks: 0
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "QUARTZ_BLOCK"
    PortalColor: "default"
    PortalParticleType: "portal"
    PortalMobType: "zombie_pigman"
    PortalMobSpawnChance: 2000
    IsOTGPlus: true
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: true
    FogColorRed: 0.90586
    FogColorGreen: 0.67809
    FogColorBlue: 0.52605
    IsSkyColored: true
    CloudHeight: 220
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: true
    SpawnPointX: 0
    SpawnPointY: 59
    SpawnPointZ: 0
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 0
    SpectatorsGenerateChunks: true
Dimensions: []